---
- name: DUMMY YML
  hosts: production,backup
  tasks:
   - name: production backup
     copy:
      src: /tmp/answer.txt
      dest: /var/tmp/answer.txt
      mode: 0644
     when: inventory_hostname in groups ['production']
     tags:
      - nodegroup1
   - name: backup servers backup
     copy:
      src: /tmp/answer.txt
      dest: /var/tmp/answer2.txt
      mode: 0644
     when: inventory_hostname in groups ['backup']
     tags:
      - nodegroup2
...