
---
- name: httpd install
  hosts: node1,node2,node3
  tasks:
   - name: httpd install
     yum:
      name: httpd
      state: latest
   - name: httpd service start
     service:
      name: httpd
      state: started
   - name: enable the service
     service:
      name: httpd
      enabled: yes